---
- name: '[dependencies] Install fontconfig package on Darwin'
  homebrew:
    update_homebrew: yes
    name:
      - fontconfig
      - git
    state: latest
  become: no
  when: "'Darwin' in ansible_os_family"
  tags:
    - terminus_powerline
    - terminus_powerline_dependencies

- name: '[dependencies] Install fontconfig package on Linux'
  package:
    name:
      - fontconfig
      - git
    state: latest
  become: yes
  when: "'Debian' in ansible_os_family"
  tags:
    - terminus_powerline
    - terminus_powerline_dependencies
...
